### PR TITLE
Set up killProcess to ensure PhantomJS is stopped, including children

### PR DESCRIPTION
**Pull request by grantlucas**
It seems that `proc_terminate` doesn't reliably shut down child processes on Windows and Linux. OSX seems to be fine

A new method of `killProcess` has been set up that will use Windows specific `taskkill` and Unix's `kill` to stop the process and its children.

This in the aim to resolve issue #20 and to mitigate issue #25.

### CODE REVIEW

**Comment by grantlucas** [comment]
@Laykou Based on PR #17, is it safe to assume you're using Phantoman on Windows? If so, would you be able to give this PR a test and let me know if it still works alright for you? I don't have any Windows based systems to test it out on :disappointed:

I promise there's :cake: as a reward.

**Comment by grantlucas** [comment]
[Requested review from those experiencing the non-stopping issue](https://github.com/site5/phantoman/issues/20#issuecomment-111546228)

**Comment by igorsantos07** [comment]
Will take a look by monday. Is there cake for :penguin: users as well? :yum:

**Comment by grantlucas** [comment]
:cake: Of course

**Comment by Laykou** [comment]
@grantlucas Hi I see your request, I'll do my best. Currently I'm not using the phantoman .. You know, there is never time to write tests and you need to develop :D haha but I'll try it on windows as soon as possible :)

**Comment by grantlucas** [comment]
Thanks @Laykou. I really just want to make sure it runs and stops on Windows still due to [the changes in how PhantomJS is stopped](https://github.com/site5/phantoman/pull/26/files#diff-cde17793c3887565ae14ec6fe4793365R233). So if it still properly stops for you I'm happy :smile:

**Comment by TrafeX** [comment]
I've tested it, but it doesn't solve issue #20 :(
The process is still running:
```bash
vagrant   5267  5.8  3.7 2250332 76884 pts/2   Sl+  15:58   2:09 /vagrant/vendor/phantomjs/phantomjs/bin/phantomjs --webdriver=4444 --ignore-ssl-errors=true
```

Maybe it's because the testsuite is quite large and the PhantomJS process is running for +/- 30 minutes.

**Comment by grantlucas** [comment]
@TrafeX 

- Is that PID a child process or the original process?
- If you start your suite and manually run `kill -9 {PID}` does that stop all PhantomJS instances properly?

**Comment by grantlucas** [comment]
I haven't been able to replicate, as of yet, the non-stopping PhantomJS so this is tough to debug/fix :disappointed:

**Comment by TrafeX** [comment]
I've managed to fix this by adding `exec` to the PhantomJS command.
This is a known issue, see: https://github.com/symfony/symfony/issues/5759 https://bugs.php.net/bug.php?id=39992

**Comment by grantlucas** [comment]
Looks like we'll need to set up the use of `exec` for Unix environments. I'll close this PR when the replacement one goes up.

**Pull request closed without merging**
