### PR TITLE
Add SSL and remote debugger options.

### PR DESCRIPTION
**Pull request by oblogic7**
Added option for SSL protocol type and remote debugger port specification.  Also added output of the generated command for verification of configuration during runtime.

image

### CODE REVIEW

**Comment by grantlucas** [comment]
Thanks for the submission @oblogic7! Just a few requests:

- Once ready, remove any debugging output added in the course of setting up this PR.
- Documentation for Readme file
  - Can you add the following to the [Other](https://github.com/site5/phantoman#other) section in the readme?

```
- `sslProtocol: [sslv3|sslv2|tlsv1|any]`
    - Sets the SSL protocol for secure connections (default is `SSLv3`).
- `remoteDebuggerPort: {port}`
    - Starts PhantomJS in a debug harness and listens on the specified port
```

**Comment by oblogic7** [comment]
I have updated the readme file as requested.  

That is not debug output, but is an intentional addition to the output.  Many users, such as myself, already have phantomjs commands that are being used for our testing.  This output is helpful for users to verify that the phantoman configuration matches the required setup that was already in place.  It can also be helpful for cases where the phantomjs configuration needs to be adjusted when using different Codeception environments.

**Comment by grantlucas** [comment]
Ah alright. How about for this PR, just the new options get added and I'll setup a PR right now that has some "verbose" output for those that would like it. It'll include the command used at least and I'll see what else might be useful to have output.

I agree that having this output in some cases can be really useful, especially development. So maybe a debug mode is in order. Thoughts on that?

**Comment by grantlucas** [comment]
Thanks for the readme updates!

**Comment by oblogic7** [comment]
I like that solution.  I will remove the output from my branch so you can merge.

**Pull request merged**
